name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0' # Synchronise this version with the devcontainer.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test,dev]

    - name: Run Black
      run: black --check .

    - name: Test with pytest
      run: |
        pytest --cov --cov-report=xml

    - name: Test with pytest (JIT disabled)
      env:
        NUMBA_DISABLE_JIT: 1
      run: |
        pytest --cov --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
