name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'  # Set this to your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Build Documentation
      run: |
        cd docs  # Change to your documentation directory
        sphinx-build -b html . _build

    - name: Deploy Docs to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/_build/html
